name: Build and Release Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Ubuntu executable
        if: matrix.os == 'ubuntu-latest'
        uses: actions/download-artifact@v2
        with:
          name: executable-ubuntu-latest
          path: ./ubuntu

      - name: Download MacOS executable
        if: matrix.os == 'macos-latest'
        uses: actions/download-artifact@v2
        with:
          name: executable-macos-latest
          path: ./macos

      - name: Download Windows executable
        if: matrix.os == 'windows-latest'
        uses: actions/download-artifact@v2
        with:
          name: executable-windows-latest
          path: ./windows

      - name: List files for debugging
        run: ls -R

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Ubuntu asset to Release
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ubuntu/main
          asset_name: main-ubuntu-latest
          asset_content_type: application/octet-stream

      - name: Upload MacOS asset to Release
        if: matrix.os == 'macos-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos/main
          asset_name: main-macos-latest
          asset_content_type: application/octet-stream

      - name: Upload Windows asset to Release
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows/main.exe
          asset_name: main-windows-latest
          asset_content_type: application/octet-stream
