name: Build and Test Executables

# Триггеры для запуска: при push в основной ветке или при pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Определяем платформы для выполнения сборки
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.x']

    steps:
      # Шаг 1: Клонирование кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установка Python нужной версии
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Шаг 4: Сборка исполняемого файла
      - name: Build executable
        run: pyinstaller --onefile main.py

      # Шаг 5: Тестирование собранного исполняемого файла (если применимо)
      # Этот шаг можно адаптировать под ваши нужды или удалить, если тестирование не требуется
      - name: Test executable (Windows/Linux only)
        if: runner.os != 'macOS'
        run: |
          ./dist/main --help

      # Шаг 6: Загрузка артефакта для скачивания
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: executable-${{ matrix.os }}
          path: dist/
